version: '3'
services:
  front-site:
    image: namdh/miniwebserver:latest
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumns/letsencrypt/etc/:/etc/mini-web-server/certs/:ro
      - ./volumns/mini-web-server/logs/:/app/logs/
    env_file:
      - ./settings.env

  
